Repository BadDevel0pers/covid-patrol, pull requests merged in 2020-08, with the labels that each got.

#3 - create component for a Footer
  components/Footer.js
  components/theme.js
  pages/_app.js
  pages/index.js
Labels: ready for review

#4 ADD: base map
  README.md
  components/map/Map.js
  components/map/MapChart.js
  package-lock.json
  package.json
  pages/index.js
  yarn.lock
Labels: ready for review

#11 - attempt to fix styled components warning on SSR
  .babelrc.js
  components/map/MapChart.js
  package-lock.json
  package.json
  pages/_app.js
  pages/_document.js
Labels: in progress

#13 EDIT: disable popover overlay
  components/map/MapChart.js
  components/map/MapPopover.js
Labels: in progress

#14 EDIT: search, ADD: map sidebar
  components/map/MapChart.js
  components/map/MapSearch.js
  components/map/MapSideBar.js
  components/theme.js
Labels: ready for review

#16 ADD: change zoom and position by clicking on map
  components/map/MapChart.js
  components/map/MapSearch.js
  helpers/map/getMapHeight.js
  pages/index.js
Labels: ready for review

#17 update layout
  components/HeaderNavbar.js
  components/map/Map.js
  components/map/MapChart.js
  package.json
  pages/_app.js
  pages/index.js
Labels: ready for review

#18 EDIT: refactor search & small fixes for footer & switch styles
  components/Footer.js
  components/map/MapChart.js
  components/map/MapSearch.js
  components/map/MapSideBar.js
Labels: ready for review

#19 ADD: destinations inputs & map legend. DEL: sidebar search
  components/CountriesAutoComplete.js
  components/map/MapChart.js
  components/map/MapDestinations.js
  components/map/MapLegend.js
  components/map/MapPopover.js
  components/map/MapSearch.js
  components/map/MapSideBar.js
  components/theme.js
  helpers/map/getMapHeight.js
Labels: ready for review

#21 - add API normalizer for countries endpoint
  pages/api/countries.js
Labels: ready for review

#23 ADD: versel config for enable caching
  vercel.json
Labels: ready for review

#24 Map popover
  components/map/MapChart.js
  components/map/MapPopover.js
  helpers/advisoryIcons.js
Labels: ready for review

#27 ADD: PWA
  next.config.js
  package-lock.json
  package.json
  pages/_document.js
  static/icons/icon-192x192.png
  static/icons/icon-196x196.png
  static/icons/icon-256x256.png
  static/icons/icon-384x384.png
  static/icons/icon-512x512.png
  static/manifest.json
Labels: enhancement, ready for review

#25 first release
  .babelrc.js
  .editorconfig
  .env-example
  .eslintrc.js
  .gitignore
  .prettierrc
  README.md
  components/CountriesAutoComplete.js
  components/Footer.js
  components/HeaderNavbar.js
  components/map/Map.js
  components/map/MapChart.js
  components/map/MapDestinations.js
  components/map/MapLegend.js
  components/map/MapPopover.js
  components/map/MapSideBar.js
  components/map/MapTooltip.js
  components/theme.js
  helpers/advisoryIcons.js
  helpers/countryToFlagCode.js
  helpers/map/getMapHeight.js
  helpers/map/mapData.js
  next.config.js
  package-lock.json
  package.json
  pages/_app.js
  pages/_document.js
  pages/api/countries.js
  pages/index.js
  public/favicon.ico
  static/icons/icon-192x192.png
  static/icons/icon-196x196.png
  static/icons/icon-256x256.png
  static/icons/icon-384x384.png
  static/icons/icon-512x512.png
  static/manifest.json
  vercel.json
Labels: ready for review
